### ISSUE TITLE
No of the project spring-cloud have pom.xml 

### ISSUE THREAD

**Issue by keshavjha1** [Nasruddin/spring-boot-based-microservices#12]
/Users/keskuma2/Library/Java/JavaVirtualMachines/corretto-17.0.4.1/Contents/Home/bin/java -Dmaven.multiModuleProjectDirectory=/Users/keskuma2/IdeaProjects/spring-boot-based-microservices -Dmaven.home=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3 -Dclassworlds.conf=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/bin/m2.conf -Dmaven.ext.class.path=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven-event-listener.jar -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=59623:/Applications/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds.license:/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar org.codehaus.classworlds.Launcher -Didea.version=2022.1.3 clean
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module /Users/keskuma2/IdeaProjects/spring-boot-based-microservices/spring-cloud/eureka-server/pom.xml of /Users/keskuma2/IdeaProjects/spring-boot-based-microservices/pom.xml does not exist @ 
[ERROR] Child module /Users/keskuma2/IdeaProjects/spring-boot-based-microservices/spring-cloud/gateway/pom.xml of /Users/keskuma2/IdeaProjects/spring-boot-based-microservices/pom.xml does not exist @ 
[ERROR] Child module /Users/keskuma2/IdeaProjects/spring-boot-based-microservices/spring-cloud/authorization-server/pom.xml of /Users/keskuma2/IdeaProjects/spring-boot-based-microservices/pom.xml does not exist @ 
[ERROR] Child module /Users/keskuma2/IdeaProjects/spring-boot-based-microservices/spring-cloud/config-server/pom.xml of /Users/keskuma2/IdeaProjects/spring-boot-based-microservices/pom.xml does not exist @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.javatab.microservices:student-course-system:1.0.0 (/Users/keskuma2/IdeaProjects/spring-boot-based-microservices/pom.xml) has 4 errors
[ERROR]     Child module /Users/keskuma2/IdeaProjects/spring-boot-based-microservices/spring-cloud/eureka-server/pom.xml of /Users/keskuma2/IdeaProjects/spring-boot-based-microservices/pom.xml does not exist
[ERROR]     Child module /Users/keskuma2/IdeaProjects/spring-boot-based-microservices/spring-cloud/gateway/pom.xml of /Users/keskuma2/IdeaProjects/spring-boot-based-microservices/pom.xml does not exist
[ERROR]     Child module /Users/keskuma2/IdeaProjects/spring-boot-based-microservices/spring-cloud/authorization-server/pom.xml of /Users/keskuma2/IdeaProjects/spring-boot-based-microservices/pom.xml does not exist
[ERROR]     Child module /Users/keskuma2/IdeaProjects/spring-boot-based-microservices/spring-cloud/config-server/pom.xml of /Users/keskuma2/IdeaProjects/spring-boot-based-microservices/pom.xml does not exist
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

Process finished with exit code 1

**Comment by Nasruddin** [comment]
@keshavjha1 Thanks for pointing out the issue. I have made the changes!
