### ISSUE TITLE
role repository required annotation

### ISSUE THREAD

**Issue by rahulpawar02** [Nasruddin/spring-boot-based-microservices#8]
role repository need to be annotated by @Repository.

@Repository
public interface RoleRepository extends CrudRepository<Role, String> {
}

**Comment by Nasruddin** [comment]
Please go ahead and create a PR.

**Comment by Nasruddin** [comment]
Made the changes

**Comment by Nasruddin** [comment]
Please feel free to make changes and raise a PR.
